name: ahappybot
region: nyc
services:
- http_port: 4000
  image:
    registry: silbermm
    registry_type: DOCKER_HUB
    repository: ahappybot
    tag: __APP_VERISON__
  instance_count: 1
  instance_size_slug: basic-xxs
  name: ahappybot
  routes:
  - path: /
- envs:
  - key: SPOTIFY_CLIENT_ID
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: __SPOTIFY_CLIENT_ID__
  - key: SPOTIFY_CLIENT_SECRET
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: __SPOTIFY_CLIENT_SECRET__
  - key: SPOTIFY_REFRESH_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: __SPOTIFY_REFRESH_TOKEN__
  - key: TWITCH_PASS
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: __TWITCH_PASS__
  - key: TWITCH_USER
    scope: RUN_AND_BUILD_TIME
    value: a_happybot
  - key: DISCOGS_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: __DISCOGS_TOKEN__
